# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'people_up.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow

class People(QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(324, 475)
        MainWindow.setStyleSheet("background-color: rgb(153, 193, 241);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 30, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit_name = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_name.setGeometry(QtCore.QRect(70, 70, 191, 31))
        self.lineEdit_name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 200, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(120, 110, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_klad = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_klad.setGeometry(QtCore.QRect(70, 160, 191, 31))
        self.lineEdit_klad.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_klad.setObjectName("lineEdit_klad")
        self.pushButton_tovar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_tovar.setGeometry(QtCore.QRect(110, 290, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_tovar.setFont(font)
        self.pushButton_tovar.setStyleSheet("background-color: rgb(143, 240, 164);")
        self.pushButton_tovar.setObjectName("pushButton_tovar")
        self.pushButton_exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(110, 340, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_exit.setFont(font)
        self.pushButton_exit.setStyleSheet("background-color: rgb(246, 97, 81);")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(70, 240, 191, 31))
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 324, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Имя"))
        self.label_2.setText(_translate("MainWindow", "Должность"))
        self.label_4.setText(_translate("MainWindow", "Фамилия "))
        self.pushButton_tovar.setText(_translate("MainWindow", "Добавить"))
        self.pushButton_exit.setText(_translate("MainWindow", "Выход"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Грузчик"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Водитель погрузчика"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Разнорабочий"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Уборщик"))
