# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sklad.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow

class Sklad(QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(807, 640)
        MainWindow.setStyleSheet("background-color: rgb(153, 193, 241);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(20, 60, 451, 401))
        self.tableView.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableView.setObjectName("tableView")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(350, 20, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_tovar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_tovar.setGeometry(QtCore.QRect(589, 80, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_tovar.setFont(font)
        self.btn_tovar.setStyleSheet("background-color: rgb(143, 240, 164);")
        self.btn_tovar.setObjectName("btn_tovar")
        self.btn_delete = QtWidgets.QPushButton(self.centralwidget)
        self.btn_delete.setGeometry(QtCore.QRect(590, 150, 151, 41))
        self.btn_delete.setStyleSheet("background-color: rgb(246, 97, 81);")
        self.btn_delete.setObjectName("btn_delete")
        self.btn_exit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exit.setGeometry(QtCore.QRect(650, 560, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_exit.setFont(font)
        self.btn_exit.setStyleSheet("background-color: rgb(246, 97, 81);")
        self.btn_exit.setObjectName("btn_exit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 807, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Cклад"))
        self.btn_tovar.setText(_translate("MainWindow", "Добавление товара"))
        self.btn_delete.setText(_translate("MainWindow", "Удаление товара"))
        self.btn_exit.setText(_translate("MainWindow", "Выход"))
