# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tovar.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow

class Tovar(QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(499, 435)
        MainWindow.setStyleSheet("background-color: rgb(153, 193, 241);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 30, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit_name = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_name.setGeometry(QtCore.QRect(30, 70, 191, 31))
        self.lineEdit_name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 140, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_quant = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_quant.setGeometry(QtCore.QRect(30, 180, 191, 31))
        self.lineEdit_quant.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_quant.setObjectName("lineEdit_quant")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(330, 140, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(330, 20, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_gorod = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_gorod.setGeometry(QtCore.QRect(280, 70, 191, 31))
        self.lineEdit_gorod.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_gorod.setObjectName("lineEdit_klad")
        self.pushButton_tovar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_tovar.setGeometry(QtCore.QRect(200, 270, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_tovar.setFont(font)
        self.pushButton_tovar.setStyleSheet("background-color: rgb(143, 240, 164);")
        self.pushButton_tovar.setObjectName("pushButton_tovar")
        self.pushButton_exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(200, 320, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_exit.setFont(font)
        self.pushButton_exit.setStyleSheet("background-color: rgb(246, 97, 81);")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(310, 180, 141, 31))
        self.dateEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dateEdit.setObjectName("dateEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 499, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Название товара"))
        self.label_2.setText(_translate("MainWindow", "Колличество"))
        self.label_3.setText(_translate("MainWindow", "Дата привоза"))
        self.label_4.setText(_translate("MainWindow", "Город"))
        self.pushButton_tovar.setText(_translate("MainWindow", "Добавить"))
        self.pushButton_exit.setText(_translate("MainWindow", "Выход"))
