# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'income.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow

class Income(QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        MainWindow.setStyleSheet("background-color: rgb(181, 131, 90)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 0, 231, 71))
        self.label.setObjectName("label")
        self.lineEdit_ip = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ip.setGeometry(QtCore.QRect(220, 120, 181, 31))
        self.lineEdit_ip.setStyleSheet("background-color: rgb(222, 221, 218);")
        self.lineEdit_ip.setObjectName("lineEdit_ip")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 70, 131, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(260, 190, 81, 31))
        self.label_3.setObjectName("label_3")
        self.lineEdit_income = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_income.setGeometry(QtCore.QRect(220, 240, 181, 31))
        self.lineEdit_income.setStyleSheet("background-color: rgb(222, 221, 218);")
        self.lineEdit_income.setObjectName("lineEdit_income")
        self.pushButton_db = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_db.setGeometry(QtCore.QRect(260, 310, 111, 41))
        self.pushButton_db.setStyleSheet("font: 12pt \"Open Sans\";")
        self.pushButton_db.setObjectName("pushButton_db")
        self.pushButton_exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(509, 375, 91, 41))
        self.pushButton_exit.setStyleSheet("background-color: rgb(165, 29, 45);\n"
"font: 12pt \"Open Sans\";")
        self.pushButton_exit.setObjectName("pushButton_exit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Добавить Доход</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Организация</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Сумма</span></p></body></html>"))
        self.pushButton_db.setText(_translate("MainWindow", "Добавить"))
        self.pushButton_exit.setText(_translate("MainWindow", "Закрыть"))
