# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow

class Auth(QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(318, 498)
        MainWindow.setStyleSheet("background-color: rgb(205, 171, 143)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_login = QtWidgets.QLabel(self.centralwidget)
        self.label_login.setGeometry(QtCore.QRect(80, 40, 151, 61))
        self.label_login.setObjectName("label_login")
        self.label_password = QtWidgets.QLabel(self.centralwidget)
        self.label_password.setGeometry(QtCore.QRect(110, 180, 91, 31))
        self.label_password.setObjectName("label_password")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(70, 100, 181, 31))
        self.lineEdit.setStyleSheet("background-color: rgb(181, 131, 90)")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_password = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_password.setGeometry(QtCore.QRect(70, 230, 181, 31))
        self.lineEdit_password.setStyleSheet("background-color: rgb(181, 131, 90)")
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.btn_auth = QtWidgets.QPushButton(self.centralwidget)
        self.btn_auth.setGeometry(QtCore.QRect(110, 290, 101, 41))
        self.btn_auth.setStyleSheet("background-color: rgb(181, 131, 90)")
        self.btn_auth.setObjectName("btn_auth")
        self.btn_exit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exit.setGeometry(QtCore.QRect(110, 370, 101, 41))
        self.btn_exit.setStyleSheet("background-color: rgb(181, 131, 90)")
        self.btn_exit.setObjectName("btn_exit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 318, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_login.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Логин</span></p></body></html>"))
        self.label_password.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Пароль</span></p></body></html>"))
        self.btn_auth.setText(_translate("MainWindow", "Войти"))
        self.btn_exit.setText(_translate("MainWindow", "Выход"))
